# Default configuration for Blackbox Exporter modules
defaults:
  module:
    name: "default_module"
    version: "1.0.0"
    description: ""
    timeout: "5s"
  
  http:
    method: "GET"
    valid_status_codes: [200, 201, 204]
    valid_http_versions: ["HTTP/1.1"]
    preferred_ip_protocol: "ip4"
    ip_protocol_fallback: true
    no_follow_redirects: false
    fail_if_ssl: false
    fail_if_not_ssl: false
    headers: {}
    content_type: "application/json"
    request_body: ""
    fail_if_body_matches: []
    fail_if_body_not_matches: []
    
  tcp:
    preferred_ip_protocol: "ip4"
    ip_protocol_fallback: true
    
  ping:
    packet_count: 4
    
  tls:
    enabled: false
    ca_file: "/etc/blackbox/certs/ca.pem"
    cert_file: "/etc/blackbox/certs/client.pem"
    key_file: "/etc/blackbox/certs/client.key"
    server_name: "my.api.server.com" 