modules:
  httpx:
    prober: http
    timeout: 15s
    http:
      method: GET
      valid_status_codes:
        - 200
        - 201
        - 204
      valid_http_versions:
        - HTTP/1.0
        - HTTP/1.1
        - HTTP/2.0
      preferred_ip_protocol: ip4
      ip_protocol_fallback: true
